### ISSUE TITLE
Tokenization

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/introdemo#17]
This portion of the code splits the transcription on various delimiters. But when there are two delimiters in a row, this sometimes creates an array with values === "" (blank). So I had to add code to check that the value isn't blank before pushing the new word to the words array. However, this wouldn't be necessary if the regular expression could be rewritten so as to treat multiple delimiters as one.

	var tokens = transcription.split(/[\u3000 .,!?]/g);
	
	var words = []
	tokens.forEach(function(token) {
		if (token !== '') {
			var word = new Word(token, '', '');
			words.push(word);
		}
	});

**Comment by metasyn** [comment]
You just need a `+` to make the expression greedy.

**Comment by metasyn** [comment]
I think that maybe instead of making a new issue, I'll comment here.

What do you think of expanding the current split punctuation? 

Certain expansions I think are a bit more necessary than others, e.g.:

 - quotes, double
 - quotes, single
 - brackets, parenthesis, angles
 - slashes
 - colon, semi-colon
 - probably more? 

are more important than an interrobang.

Furthermore, maybe apostrophes for English possessive affixes? Dashes for for things like qu'est-ce que in French? Upside down exclamation and question mark in Spanish ?

**Comment by dwhieb** [comment]
@amundo and I were just chatting about this yesterday. Ideally, we'll want the tokenize function to be as general as possible, so we can reuse it in multiple places, with a variety of different languages. It's unrealistic to expect we'll be able to create one set of delimiters that works for every orthography in every language.

Instead, we'll have a function tokenize(string, delimiters), which gets fed the string to be tokenized and an array of delimiters. This array of delimiters will most often come from an orthography object, which will have as one of its properties a delimiters array.

For the purposes of introdemo, however, we're just going to specify the delimiters ourselves. I do think it would be useful to get all the most likely punctuation accounted for - everything you listed above. Would you be willing to add those to the delimiters regexp? Pat and I will massage the function later but use that delimiter list.
